### ISSUE TITLE
lack of utils.py and processed data 

### ISSUE THREAD

**Issue by xuangu-fang** [liuwj2000/TIDER#1]
I'm trying to follow this remarkable work, but this repo lacks the dependency of utils.py nor the processed data example. The original size of data, the GUANG ZHOU dataset, for example,  doesn't match the size claimed in the paper. 

It would be greatly appreciated if the author could release the utils.py and the data-process script /processed data example.

**Comment by liuwj2000** [comment]
Hi Fang, we have updated our TIDER code. Now it does not need  utils.py anymore. By merely running the TIDER.py code, it is enough.

For data processing, we have also updated the readme file which tells how to process them.

**Comment by xuangu-fang** [comment]
> Hi Fang, we have updated our TIDER code. Now it does not need utils.py anymore. By merely running the TIDER.py code, it is enough.
> 
> For data processing, we have also updated the readme file which tells how to process them.

Thank you!
